### PR TITLE
Attr coercion behavior change

### PR DESCRIPTION
**Pull request by Justineo**
This RFC describes the changes we intend to make about attribute coercion behavior.

[Rendered](https://github.com/vuejs/rfcs/blob/attr-coercion/active-rfcs/0000-attribute-coercion-behavior.md)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
How `attr="attr"` should behave? `draggable="attr"` or `draggable=""` or `draggable="true"`?

See:
https://github.com/vuetifyjs/vuetify/blob/3a510e8af57d76da660c6b4a407f7940fefae5cb/packages/vuetify/src/mixins/detachable/index.ts#L126

**Comment by Justineo** [comment]
> How `attr="attr"` should behave? `draggable="attr"` or `draggable=""` or `draggable="true"`?

This RFC only affects attributes defined by `v-bind`. Otherwise the attribute won't be coerced.

**Comment by yyx990803** [comment]
This RFC is now in final comments stage. An RFC in final comments stage means that:

The core team has reviewed the feedback and reached consensus about the general direction of the RFC and believe that this RFC is a worthwhile addition to the framework.
Final comments stage does not mean the RFC's design details are final - we may still tweak the details as we implement it and discover new technical insights or constraints. It may even be further adjusted based on user feedback after it lands in an alpha/beta release.
If no major objections with solid supporting arguments have been presented after a week, the RFC will be merged and become an active RFC.

**Comment by xSorc** [comment]
@Justineo link is broken. I suppose this is valid link?
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0024-attribute-coercion-behavior.md

**Pull request merged**
