### PR TITLE
Remove keyCode support in v-on

### PR DESCRIPTION
**Pull request by yyx990803**
- Drop support for using numbers (keyCodes) as `v-on` modifiers
- Remove `config.keyCodes`

[`KeyboardEvent.keyCode` has been deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and we already have support for using [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) as modifiers.

[Rendered](https://github.com/vuejs/rfcs/blob/drop-keycode/active-rfcs/0000-drop-keycode-support.md)

### CODE REVIEW

**Comment by Meekohi** [comment]
Browser support for `.code` is still pretty bad: https://caniuse.com/#feat=keyboardevent-code

**Comment by leopiccionia** [comment]
`KeyboardEvent.key` may often return values that aren't template-friendly, like `.`, `=`, `>`, etc. I can't imagine common cases where those would be handy, though. On the worst hypothesis, one can handle the `key` inside event handler.

An exception would be the space bar (` `), that even gained a "named" modifier in 2.x (`.space`). Will "named" 2.x modifiers like this be kept? Some of them (`.esc`, the four arrows) have non-standard `key`s in IE11, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values).

**Comment by yyx990803** [comment]
@leopiccionia yes, 2.x built-in aliases will be kept.

**Comment by yyx990803** [comment]
This RFC is now in final comments stage. An RFC in final comments stage means that:

The core team has reviewed the feedback and reached consensus about the general direction of the RFC and believe that this RFC is a worthwhile addition to the framework.
Final comments stage does not mean the RFC's design details are final - we may still tweak the details as we implement it and discover new technical insights or constraints. It may even be further adjusted based on user feedback after it lands in an alpha/beta release.
If no major objections with solid supporting arguments have been presented after a week, the RFC will be merged and become an active RFC.

**Pull request merged**
