### PR TITLE
Dispatch & Broadcast API

### PR DESCRIPTION
**Pull request by wspl**
A proposal that bring back the `$dispatch` and `$broadcast` APIs. I am still waiting for new features of Vue 3.0 to make this API more elegant.

[Rendered](https://github.com/wspl/vue-rfcs/blob/dispatch-broadcast-api/active-rfcs/0000-dispatch-broadcast-api.md)

### CODE REVIEW

**Comment by posva** [comment]
Hi thanks for the detailed proposal but we removed them for a reason. Please see https://vuejs.org/v2/guide/migration.html#dispatch-and-broadcast-replaced for a detailed explanation.

We prefer a data-driven approach whenever possible because it makes everything easier to reason about and to debug.
However, if in your specific application, dispatch/broadcast fits better, you can always implement it to use it and you showed in the Element codebase and I think that is how it should be because of the impacts mentioned in the link above

**Comment by HerringtonDarkholme** [comment]
Similar functionality can be implemented via [provide/inject](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#dependency-injection). We can inject an event emitter to every component that needs to listen dispatched events.
Injection based event emitter is better since it supports namespaced events out of box (just add a new provide/inject symbol). And we can debug where the event might be emitted by injection symbol instead of grepping some event string.

**Comment by wspl** [comment]
> Similar functionality can be implemented via [provide/inject](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#dependency-injection). We can inject an event emitter to every component that needs to listen dispatched events.
> Injection based event emitter is better since it supports namespaced events out of box (just add a new provide/inject symbol). And we can debug where the event might be emitted by injection symbol instead of grepping some event string.

I used to use `provide` and `inject` to implement this feature. It works for calling the method of parent/grandparent component from child component, but the reverse is very troublesome (if it encounter a component structural change (add, remove, cross-level move) or go through a vue-portal component, this is no longer applicable.)

I think this is a very common feature. It does have a bunch of alternatives, but it would be great if it works out of the box.

**Comment by Nandiin** [comment]
While `broadcast/dispatch` pattern does have significant value in certain usecases, it should be kept away from the core library for following reasons:
1. Better solutions, like `Vuex,` are available if arbitrary component communication is necessary, without the brittleness that `broadcast/dispatch` brings.
2. `broadcast/dispatch` is easily implementable on userland. 
    
    In Vue 2.x, using a external api like `EventBus` may seem exotic since all the official apis either are bound on `this` or have a place on `component options`. However, with the introduction of [`Function-based Component API`](https://github.com/vuejs/rfcs/pull/42), use of an external `EventBus` like api would seem much more consistent with the Vue official apis.

**Pull request closed without merging**
