### PR TITLE
Allow displaying a View different from where the user currently is at

### PR DESCRIPTION
**Pull request by posva**
[Rendered](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0036-router-view-route-prop.md)

Enables Modals that change the URL

### CODE REVIEW

**Comment by nainardev** [comment]
so, finally we can have twitter or ig like modals? thanks :blush:

**Comment by posva** [comment]
There is an example here: https://github.com/vuejs/vue-router-next/tree/master/e2e/modal

**Comment by posva** [comment]
This RFC is now in final comments stage. An RFC in final comments stage means that:

The core team has reviewed the feedback and reached consensus about the general direction of the RFC and believes that this RFC is a worthwhile addition to the framework.
Final comments stage does not mean the RFC's design details are final - we may still tweak the details as we implement it and discover new technical insights or constraints. It may even be further adjusted based on user feedback after it lands in an alpha/beta release.
If no major objections with solid supporting arguments have been presented after a week, the RFC will be merged and become an active RFC.

**Comment by serkodev** [comment]
> There is an example here: https://github.com/vuejs/vue-router-next/tree/master/e2e/modal

In case someone need the updated location of the `e2e/modal` source code, please visit:
https://github.com/vuejs/router/blob/main/packages/router/e2e/modal/index.ts

**Pull request merged**
