### PR TITLE
Immutable object when using computed get only

### PR DESCRIPTION
**Pull request by pikax**
[Rendered](https://github.com/pikax/rfcs/blob/immutable-computed-get/active-rfcs/0000-immutable-computed-get.md)

[codesandbox](https://codesandbox.io/s/vue-template-mwcpu)

### CODE REVIEW

**Comment by posva** [comment]
I don't think the cost of making every computed property immutable is worth since the concept of a computed property is precisely being readonly. Making the type use `Readonly`, sure, that's definitely a good thing as it has no cost

**Comment by kahirokunn** [comment]
This idea will zero cost resolve many mistakes.
I think this idea is really cool.

**Comment by pikax** [comment]
I'm using `immutable` wording to enforce the fact the readonly computed should be readonly through out, since modifying it leads to unexpected behaviour. 

Can't we warn in development if you try to modify a computed? For example prop type checking is only available in development mode

**Comment by kahirokunn** [comment]
I think zero cost static analysis is good.
Because I think debug on the runtime with typescript is not typescript way ...😢

**Comment by yyx990803** [comment]
In v3 this is the default behavior. In v2, however, implementing such behavior without native ES Proxy will be too costly.

**Comment by pikax** [comment]
@kahirokunn not everyone uses typescript, having some safeguards (such runtime and development only checks) would be helpful for some developers.


> In v3 this is the default behavior. In v2, however, implementing such behavior without native ES Proxy will be too costly.

The wording used in composition-api-rfc suggested that.

Do you think is worth to add this interactions to the documentation as an `warning`?

for example: 
> Object returned by computed property are `non-reactive` and don't affect the original instance and it will be overrided once the computed gets recalculated
example:
```js
var vm = new Vue({
  data: { a: 1 },
  computed: {
    // get only
    double: function () {
      return {
        a: this.a
    },
  }
})
vm.a   // => 1
vm.double.a // => 1
vm.a++ // => 2
vm.double.a // => 2
vm.double.a++ // => 3
vm.a  // => 2
vm.a--  // => 1
vm.double.a  // =>1
```

**Comment by danielelkington** [comment]
Sometimes it makes sense for properties in an object returned by a computed property to be mutable. Consider cases where a component's data contains an array of items and a computed property is used to point to a particular item in the array - properties can be safely mutated as you are really just changing the underlying data.

For example ([CodeSandbox](https://codesandbox.io/s/mutablecomputedproperty-h908v)):
```
<template>
  <div>
    <label>Lookup Person Id:</label>
    <input type="number" v-model="selectedPersonId">
    <br>
    <label v-if="selectedPerson">Edit Person Name:</label>
    <input v-if="selectedPerson" v-model="selectedPerson.name">
  </div>
</template>

<script>
export default {
  data: function() {
    return {
      people: [{ id: 1, name: "Jane" }, { id: 2, name: "Jack" }],
      selectedPersonId: 1
    };
  },
  computed: {
    selectedPerson: function() {
      return this.people.find(x => x.id === Number(this.selectedPersonId));
      // Safe to mutate this object (eg using v-model) because it just points
      // to something in "data"
    }
  }
};
</script>

```

**Comment by pikax** [comment]
@danielelkington thanks for bringing that point, I think that behaviour is expected. 

Then reason for this rfc is to prevent non-reactive for being modified, for example change the type of the people to be an array of numbers, and you will see your change doesn't take effect. 

The definition would be: the `computed property` is **readonly** if the property value is `not` **reactive** or **ref**.

I will update the rfc to incorporate that too.

**Comment by pikax** [comment]
https://github.com/vuejs/vue-next doesn't have this limitations.

**Pull request closed without merging**
