### PR TITLE
Slots Unification

### PR DESCRIPTION
**Pull request by yyx990803**
[Rendered](https://github.com/vuejs/rfcs/blob/slots-unification/active-rfcs/0000-slots-unification.md)

### CODE REVIEW

**Comment by posva** [comment]
Is

```js
h(Comp, () => [h('div', this.msg)])
```

equivalent to

```js
h(Comp, {
  slots: {
    default: () => [h('div', this.msg)],
  },
})
```

in v3?

**Comment by yyx990803** [comment]
@posva yes.

**Comment by YunSun-CN** [comment]
Instead of using keyword `$stable`, why not design `slot` functions as `computed` to cache vnodes?Developers should be noted in documentation that a `slot` function should be defined preserved outside the `render` function scope.

**Comment by yyx990803** [comment]
This RFC is now in final comments stage. An RFC in final comments stage means that:

- The core team has reviewed the feedback and reached consensus about the general direction of the RFC and believe that this RFC is a worthwhile addition to the framework.
- Final comments stage does **not** mean the RFC's design details are final - we may still tweak the details as we implement it and discover new technical insights or constraints. It may even be further adjusted based on user feedback after it lands in an alpha/beta release.
- If no major objections with solid supporting arguments have been presented after a week, the RFC will be merged and become an active RFC.

**Pull request merged**
