### PR TITLE
Scoped slot API for router-link

### PR DESCRIPTION
**Pull request by posva**
[Rendered](https://github.com/posva/rfcs/blob/router/link-scoped-slot/active-rfcs/0000-router-link-scoped-slot.md)

### CODE REVIEW

**Comment by Akryum** [comment]
I love it so much 😻

**Comment by Rolanddoda** [comment]
That would be awesome and very flexible

**Comment by adamwathan** [comment]
The scoped slots API looks fantastic, very well thought-out 👍 Nice job!

**Comment by Akryum** [comment]
I would change `isActive` to `isSamePath` and `isExactActive` to `isSameExact` or `isSame` (or similar), to be more consistent with `isSameQuery` and `isSameHash`.

**Comment by posva** [comment]
we can add `isSamePath` for consistency but `isActive` is more of an inclusion like `string.startsWith` than an equality. It's an equality if in #35 we use `exact="path"` though

**Comment by Akryum** [comment]
For `isActiveExact`, I'm not sure changing the behavior of passed slot props depending on other props would be a good idea.

My suggestion of slot props:

- `isActive`: true whenever `router-link-active` is applied. This is when the _path_ section of the href (without the query and hash) is included (as in `currentLocation.path.startsWith(location.path)`)
- `isSameURL`: true whenever the _fullPath_ is matched (including query and hash) (as in `currentLocation.fullPath === location.fullPath`)
- `isSamePath`: true if the path of the link matches current path
- `isSameQuery`: true if the query of the link matches current query
- `isSameHash`: true if the hash of the link matches current hash
- `isDescendant`: true if the route record matched by the `to` location is a descendant of the record matched by the current route (as in `children` (works for nested `children` as well))
- `isAscendant`: true if the route record matched by the `to` location is an ascendant of the record matched by the current route (as in current route being in `children`(works for nested routes as well))

**Comment by Akryum** [comment]
> It's an equality if in #35 we use exact="path" though

The `exact` prop shouldn't change `router-link-active` though

**Comment by posva** [comment]
Adding a `isSameURL` (or `isSameFullPath` for consistency) makes me wonder if we should just leave `isSameQuery` as it is the only one that requires comparing objects and cannot be achieved comparing values in `location` and `$route` 🤔 

The reasoning behind `isExactActive` is to provide a way to know whether the `router-link-exact-active` would be applied or not. That's why it makes sense to change its behavior based on the `exact` prop. The same goes for `isActive`, its behavior also changes based on `exact`. Which just made me realize there is a confusion part on my exact prop proposal: right now providing exact changes the behavior of the active class, which will be applied only with an exact match, alongside the exact class. Having a string value would still follow that reasoning, so the link always has both classes or none of them

**Comment by Akryum** [comment]
So maybe we can just add `isSameFullPath` in addition to `isExactActive`

**Comment by Akryum** [comment]
> if we should just leave `isSameQuery` as it is the only one that requires comparing objects and cannot be achieved comparing values in `location` and `$route` 🤔 

But it would be very handy to have the others. Less cognitive load imo.

**Comment by Akryum** [comment]
## Helper slot props

### Classes

- `isActive`
- `isExactActive`

### Route comparison

- `isPathIncluded`
- `isSameFullPath`
- `isSamePath`
- `isSameQuery`
- `isSameHash`

### Route tree

- `isDescendant`
- `isAscendant`

**Comment by CesarGomezTissini** [comment]
This awesome rfcs take me with a new question: is it possible to use named router views in future (like Angular) assuming in that framework both implementations have a relation?

**Comment by JamesCoyle** [comment]
This gets a 👍 from me. I believe this would solve an issue I'm currently having.

I'm currently trying to implement a generic `tab-item` element that can be any tag (`button`, `a`, `router-link`, etc). I've currently implemented this functionality but I don't always want the tab item to be a router link. I need a clean way to handle active state by either manually setting it based on certain application state if it isn't a router-link or having it set automatically if it is a router-link. 

Ideally I'd like to be able to define a tab-item as its own component that can render as a button, anchor, or other custom component and then, if desired, wrap the router-link functionality around that without adding unnecessary DOM elements. I like this proposal as it provides access to the data router-link uses such as the href and active state which AFAIK aren't currently accessible in a reactive state. 

### Examples

Render as `a`  just using `tab-item`
```html
<!-- template -->
<tab-item tag="a" href="/tab-test" active>Tab Link</tab-item>

<!-- rendered -->
<li class="tab-item active">
    <a href="/tab-test">Tab Link</a>
</li>
```

Render as `a` by wrapping in a `router-link`
```html
<!-- template -->
<router-link to="/tab-test" v-slot="{ isActive, href }">
  <tab-item tag="a" :href="href" :active="isActive">Tab Link</tab-item>
</router-link>

<!-- rendered -->
<li class="tab-item active">
    <a href="/tab-test">Tab Link</a>
</li>
```

Render as `button` by wrapping in a `router-link`
```html
<!-- template -->
<router-link to="/tab-test" v-slot="{ isActive, navigate }">
  <tab-item tag="button" @click="navigate" :active="isActive">Tab Link</tab-item>
</router-link>

<!-- rendered -->
<li class="tab-item active">
    <button>Tab Link</button>
</li>
```

**Comment by donnysim** [comment]
Would it recognize active state when it contains children from different route trees? Like they have nothing in common, just grouped under one element?

Resources (<- should be marked as isDescendant?)
    - Users (/users)
    - Clients (/clients, active)

**Comment by posva** [comment]
if you are on Resources and Users and clients and children of that route record, then yes, isDescendant will be true for those two links

**Comment by donnysim** [comment]
Children as in template composition wise, not router configuration wise?

**Comment by posva** [comment]
oh, always related to routing configuration. We are comparing routing records at the end

**Comment by donnysim** [comment]
Was hoping it could also do it template wise, as there's often groups of routes that are not in the same tree, but I think it will be solvable if there will be child route addition functionality on the router. We have modules that register separate routes, and because of the current router state, all we can do is add a duplicate base route to the root that wraps the intended route as children.

I also wonder if/how it'll make certain scenarios simpler? Taking sidebars as an example, on page open, you want the active tree to be expanded by default, but it also should not force it to stay active as the user might collapse it. Though this might be something to solve in userland with a wrapper component?.

**Comment by plehnen** [comment]
I propose renaming `navigate` to `onNavigate` making it more implicit that this is an event handler (same reason why isActive isn't called just active)

**Comment by posva** [comment]
Thanks but navigate is an action that you attach as an event handler, so having a verb makes more sense imo

Eduardo San Martin Morote

**Comment by posva** [comment]
I updated the RFC to include only the safe information. This API has already been implemented in vue-router v3 so any new breaking changes would only be implemented in v4

This RFC is now in final comments stage. An RFC in final comments stage means that:

The core team has reviewed the feedback and reached consensus about the general direction of the RFC and believe that this RFC is a worthwhile addition to the framework.
Final comments stage does not mean the RFC's design details are final - we may still tweak the details as we implement it and discover new technical insights or constraints. It may even be further adjusted based on user feedback after it lands in an alpha/beta release.
If no major objections with solid supporting arguments have been presented after a week, the RFC will be merged and become an active RFC.

**Comment by cawa-93** [comment]
@posva Shouldn't the Rendered link be updated?

**Pull request merged**
