### PR TITLE
Optional props declaration

### PR DESCRIPTION
**Pull request by yyx990803**
[Rendered](https://github.com/vuejs/rfcs/blob/optional-props/active-rfcs/0000-optional-props-declaration.md)

### CODE REVIEW

**Comment by sqal** [comment]
> In addition, in this case this.$attrs and this.$props will be pointing to the same object.

How in this case would be handled different props casing? Will props exposed in `$props` still be in kebab-case and in `$attrs` as defined on the component? 

`<comp prop-a="a" propB="b" />`
```
$props['prop-a'] // or would it be propA?
$props.propB
```

**Comment by posva** [comment]
it would make sense to always receive a camel-cased in js no matter what version is used on the template

**Comment by houd1ni** [comment]
@posva you've written `camel-cased` in kebab. Read it twice before getting it :)

**Comment by gregaton** [comment]
> When a component has no props declarations, all attributes passed by the parent are exposed in this.$props.

What would happen if there are props declared?

I really like the explicit props declaration. It's like a contract between a child and its parent component. Would be even nicer if we could declare events but I digress.

Anyway, I would be quite upset if people in my team would stop declaring props.
Maybe it could be considered to only allow this feature for function components?

**Comment by houd1ni** [comment]
@gregaton Functional components aren't those just pure templates as we have still known. Look at https://github.com/vuejs/rfcs/pull/27#issuecomment-481014891

So, I suppose, it's better to think how to optionally prevent teammates from not declaring props in particular teams and cases. I'm into it, by the way.

**Comment by gregaton** [comment]
> @gregaton Functional components aren't those just pure templates as we have still known. Look at [#27 (comment)](https://github.com/vuejs/rfcs/pull/27#issuecomment-481014891)

It sounds like it but I know too little about the implementation details to say if it's feasible or not.

**Comment by pikax** [comment]
Sounds a bit confusing `$attrs` and `$props` sharing the same values.

If we declare `props` does it exclude the declared from `$attrs`?

What will be the recommended way to access passed values to the component? Seems the newcomers would probably abuse `$attrs` since it does the same as `$props`.

**Comment by gustojs** [comment]
Is that an "all or nothing" approach or can we declare some props and still let the component accept other props?

**Comment by yyx990803** [comment]
@gustojs anything not explicitly declared goes into `$attrs`.

**Comment by yyx990803** [comment]
This RFC is now in final comments stage. An RFC in final comments stage means that:

- The core team has reviewed the feedback and reached consensus about the general direction of the RFC and believe that this RFC is a worthwhile addition to the framework.
- Final comments stage does **not** mean the RFC's design details are final - we may still tweak the details as we implement it and discover new technical insights or constraints. It may even be further adjusted based on user feedback after it lands in an alpha/beta release.
- If no major objections with solid supporting arguments have been presented after a week, the RFC will be merged and become an active RFC.

**Comment by CyberAP** [comment]
Could this be limited to functional components only? As it was stated earlier props define a contract between parent and child. Leaving that out creates space for confusion. Especially when we already have `$attrs`. Have there been a huge request in leaving out props?

**Comment by thedamon** [comment]
@CyberAP I agree declaring props is preferable in most cases, but this change does not change best practices. It provides an interesting option in edgecases where being able to have all (or some) props in a bucket is convenient or more performant, and providing some alternate ways to pass data. 

I don't think this feature changes that especially because these props are referenced differently (`$props.foo` vs `foo`), which maintains declaring props as the more natural way because it is "smoothest".

There could easily be an eslint rule to encourage declaring props as well.

**Pull request merged**
